- name: Installing Fish
  apt:
    name: 
      - fish
    state: latest


- name: Cloning omf 
  git:
    repo: 'https://github.com/oh-my-fish/oh-my-fish'
    dest: /opt/oh-my-fish


- name: Installing omf theme
  shell: /opt/oh-my-fish/bin/install --offline &


- name: Configuring default shell
  shell: " {{ item }}"
  with_items: 
      - echo /usr/bin/fish | sudo tee -a /etc/shells
      - chsh -s /usr/bin/fish
      - fish -c "omf install mars"

- name: Configuring Obey2 greeting
  command: cp ~/Desktop/kalima_ansible/roles/utilities/files/obey2 ~/.config/fish/obey2

- name: Configuring Oh-My-Fish
  shell: " {{ item }}"
  with_items: 
      - echo set fish_greeting >> ~/.config/fish/config.fish
      - echo "~/.config/fish/obey2" >> ~/.config/fish/config.fish

- name: Making obey2 Executable
  file:
    path: ~/.config/fish/obey2
    owner: root
    group: root
    mode: '0755'


- name: Removing useless Kali directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ~/Public
    - ~/Templates
    - ~/Music
    
- name: Mounting Shared Folders
  shell: bash /root/Desktop/mount-shared-folders

- name: Setting up wallpaper
  shell: dconf write /org/gnome/desktop/background/picture-uri "'file:///root/Desktop/kalima_ansible/roles/utilities/files/wall.jpg'"

- name: Setting favorite apps
  shell: dconf write /org/gnome/shell/favorite-apps "['firefox-esr.desktop','gnome-terminal.desktop','org.gnome.Nautilus.desktop','leafpad.desktop', 'sublime_text.desktop']"

#- name: Fixing resolution
#  shell: bash /root/Desktop/kalima_ansible/roles/utilities/files/fix.sh

  
