- name: Installing Fish
  apt:
    name: 
      - fish
    state: latest

- name: Downloading Oh-My-Fish
  uri:
    url: https://get.oh-my.fish
    follow_redirects: all
    dest: ~/omf_install

- name: Installing omf theme
  shell: " {{ item }}"
  with_items: 
      - fish /root/omf_install --path=~/.local/share/omf --config=~/.config/omf
      - echo /usr/bin/fish | sudo tee -a /etc/shells
      - chsh -s /usr/bin/fish
      - omf install mars


- name: Configuring Obey2 greeting
  command: cp ~/Desktop/kalima_ansible/roles/utilities/files/obey2 ~/.config/fish/obey2

- name: Configuring Oh-My-Fish
  shell: " {{ item }}"
  with_items: 
      - echo set fish_greeting >> ~/.config/fish/config.fish
      - echo "~/.config/fish/obey2" >> ~/.config/fish/config.fish

- name: Making obey2 Executable
  file:
    path: ~/.config/fish/obey2
    owner: root
    group: root
    mode: '0755'


- name: Removing useless Kali directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ~/Public
    - ~/Templates
    - ~/Music
    
- name: Mounting Shared Folders
  shell: bash /root/Desktop/mount-shared-folders

- name: Setting up wallpaper
  shell: dconf write /org/gnome/desktop/background/picture-uri "'file:///root/Desktop/kalima_ansible/roles/utilities/files/wall.jpg'"

- name: Setting favorite apps
  shell: dconf write /org/gnome/shell/favorite-apps "['firefox-esr.desktop', 'org.gnome.Nautilus.desktop','chromium.desktop','leafpad.desktop', 'sublime_text.desktop']"

#- name: Fixing resolution
#  shell: bash /root/Desktop/kalima_ansible/roles/utilities/files/fix.sh

  



#- name: Install Oracle 8
#  shell: " {{ item }}"
#  with_items: 
#      - wget -q -O java.tgz $(curl -s https://www.java.com/en/download/linux_manual.jsp | grep -E ".*x64.*javadl" | grep -v "RPM" | sed "s/.*href=\"//g;s/\".*//g" | head -n 1) 
#      - tar xzf java.tgz
#      - javaver="$(tar tf java.tgz | head -n1 | tr -d "/")"
#      - [ ! -d /opt/java ]
#      - mkdir /opt/java
#      - mv $javaver /opt/java
#      - update-alternatives --install "/usr/bin/java" "java" "/opt/java/$javaver/bin/java" 1
#      - update-alternatives --set java /opt/java/$javaver/bin/java
#      - rm java.tgz


