- name: Installing python-pip
  apt:
    name: 
      - python-pip 
    state: latest
    force_apt_get: yes


- name: Setting up dotnet sources
  shell: " {{ item }}"
  with_items:
      - apt-get install -y gpg
      - wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
      - mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
      - wget -q https://packages.microsoft.com/config/ubuntu/18.04/prod.list
      - mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
      - chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
      - chown root:root /etc/apt/sources.list.d/microsoft-prod.list
  

- name: Installing apt-transport-https
  apt:
    name: 
      - apt-transport-https
    state: latest

- name: Updating sources
  shell: apt-get update -y


- name: Installing dotnet2.2
  apt:
    name: 
      - dotnet-sdk-2.2
    state: latest


- name: Downloading Sublime text GPG
  uri:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    follow_redirects: all
    dest: ~/sublimehq-pub.gpg


- name: Installing sublime-text GPG
  command: apt-key add ~/sublimehq-pub.gpg
  


- name: Adding sublime-text to sources list
  shell: echo "deb https://download.sublimetext.com/ apt/stable/" > /etc/apt/sources.list.d/sublime-text.list


- name: Updating packages
  shell: apt -qqq update


- name: Installing sublime-text editor
  apt:
    name: 
      - sublime-text
    state: latest


- name: Installing sublime-text editor
  apt:
    name: 
      - mono-complete
    state: latest



- name: Cloning Tetanus 
  git:
    repo: 'https://github.com/secgroundzero/tetanus'
    dest: /opt/tetanus

- name: Cloning ad-ldap-enum 
  git:
    repo: 'https://github.com/CroweCybersecurity/ad-ldap-enum'
    dest: /opt/ad-ldap-enum

- name: Cloning LinEnum
  git:
    repo: 'https://github.com/rebootuser/LinEnum'
    dest: /opt/LinEnum

- name: Cloning Responder
  git:
    repo: 'https://github.com/lgandx/Responder'
    dest: /opt/Responder

- name: Cloning Unicorn
  git:
    repo: 'https://github.com/trustedsec/unicorn'
    dest: /opt/Unicorn

- name: Cloning ropnop's windapsearch
  git:
    repo: 'https://github.com/ropnop/windapsearch'
    dest: /opt/windapsearch


- name: Installing python-ldap
  apt:
    name: 
      - python-ldap 
    state: latest

- name: Installing pip3
  apt:
    name: 
      - python3-pip 
    state: latest


- name: Cloning ropnop's Kerberos Scripts
  git:
    repo: 'https://github.com/ropnop/kerberos_windows_scripts'
    dest: /opt/kerberos_windows_scripts

- name: Cloning nishang
  git:
    repo: 'https://github.com/samratashok/nishang'
    dest: /opt/nishang

- name: Cloning Sharpshooter
  git:
    repo: 'https://github.com/mdsecactivebreach/SharpShooter'
    dest: /opt/Sharpshooter


- name: Cloning PyKerberoast
  git:
    repo: 'https://github.com/skelsec/PyKerberoast'
    dest: /opt/PyKerberoast


- name: Cloning hidemyps
  git:
    repo: 'https://github.com/cheetz/hidemyps'
    dest: /opt/hidemyps


- name: Cloning PowerShell Empire
  git:
    repo: 'https://github.com/EmpireProject/Empire'
    dest: /opt/Empire

- name: Empire installation
  shell: echo "Empire cloning complete. Run the installation script manually"



- name: Cloning bin2c
  git:
    repo: 'https://github.com/gwilymk/bin2c'
    dest: /opt/bin2c


- name: Compiling bin2c
  command: gcc -o /opt/bin2c/bin2c /opt/bin2c/bin2c.c


- name: Installing Libre Office
  apt:
    name: 
      - libreoffice 
    state: latest

- name: Cloning Invoke-Obfuscation
  git:
    repo: 'https://github.com/danielbohannon/Invoke-Obfuscation'
    dest: /opt/Invoke-Obfuscation


- name: Cloning SprayingToolkit
  git:
    repo: 'https://github.com/byt3bl33d3r/SprayingToolkit'
    dest: /opt/SprayingToolkit


- name: Instaling SprayingToolkit
  command: pip3 install -r /opt/SprayingToolkit/requirements.txt


- name: Cloning krbrelayx
  git:
    repo: 'https://github.com/dirkjanm/krbrelayx'
    dest: /opt/krbrelayx

  
- name: Cloning WitnessMe
  git:
    repo: 'https://github.com/byt3bl33d3r/WitnessMe'
    dest: /opt/WitnessMe


- name: Instaling WitnessMe
  command: pip3 install -r /opt/WitnessMe/requirements.txt

- name: Downloading Java Oracle 8
  shell: " {{ item }}"
  with_items: 
      - wget -q -O /tmp/java.tgz $(curl -s https://www.java.com/en/download/linux_manual.jsp | grep -E ".*x64.*javadl" | grep -v "RPM" | sed "s/.*href=\"//g;s/\".*//g" | head -n 1) 
  

- name: Extracting Java to /tmp
  unarchive:
    src: /tmp/java.tgz
    dest: /tmp/

- name: Deleting java archives
  file:
    path: ~/tmp/java.tgz
    state: absent

- name: Renaming java for ease of transfer
  shell: mv /tmp/jre* /tmp/java_jre


- name: Moving Java to the right location
  shell: " {{ item }}"
  with_items:
      - mkdir /opt/java && mv /tmp/java_jre /opt/java
      - update-alternatives --install "/usr/bin/java" "java" "/opt/java/java_jre/bin/java" 1
      - update-alternatives --set java /opt/java/java_jre/bin/java
  warn: false

- name: Cloning SauronEye
  git:
    repo: 'https://github.com/vivami/SauronEye'
    dest: /opt/SauronEye


- name: Compiling SauronEye
  shell: " {{ item }}"
  with_items: 
      - xbuild /p:Configuration=Release /opt/SauronEye/src/SauronEye.sln
      - mv /opt/SauronEye/src/SauronEye/bin/Release/SauronEye.exe /opt/SauronEye/


- name: Cloning Covenant
  git:
    repo: 'https://github.com/cobbr/Covenant'
    recursive: yes 
    track_submodules: yes
    dest: /opt/Covenant

- name: Compiling Covenant
  shell: dotnet build /opt/Covenant/Covenant/


- name: Creating Cobalt Strike Aggressor scripts directory
  command: mkdir /opt/cna_scripts


- name: Cloning harleyQu1nn CNA Scripts
  git:
    repo: 'https://github.com/harleyQu1nn/AggressorScripts'
    dest: /opt/cna_scripts/harleyQu1nn/AggressorScripts


- name: Cloning bluscreenofjeff CNA Scripts
  git:
    repo: 'https://github.com/bluscreenofjeff/AggressorScripts'
    dest: /opt/cna_scripts/bluscreenofjeff/AggressorScripts


- name: Cloning vysecurity CNA Scripts
  git:
    repo: 'https://github.com/vysecurity/RdpThief'
    dest: /opt/cna_scripts/vysecurity/RdpThief


- name: Cloning PTF
  git:
    repo: 'https://github.com/trustedsec/ptf'
    dest: /opt/ptf


- name: Cloning PrivExchange
  git:
    repo: 'https://github.com/dirkjanm/PrivExchange'
    dest: /opt/PrivExchange


- name: Cloning PowerLessShell
  git:
    repo: 'https://github.com/Mr-Un1k0d3r/PowerLessShell'
    dest: /opt/PowerLessShell


- name: Cloning MailSniper
  git:
    repo: 'https://github.com/dafthack/MailSniper'
    dest: /opt/MailSniper


- name: Cloning DomainPasswordSpray
  git:
    repo: 'https://github.com/dafthack/DomainPasswordSpray'
    dest: /opt/DomainPasswordSpray


- name: Cloning RDPSpray
  git:
    repo: 'https://github.com/dafthack/RDPSpray'
    dest: /opt/RDPSpray

- name: Cloning PowerMeta
  git:
    repo: 'https://github.com/dafthack/PowerMeta'
    dest: /opt/PowerMeta


- name: Cloning HostRecon
  git:
    repo: 'https://github.com/dafthack/HostRecon'
    dest: /opt/HostRecon


- name: Cloning SharpAttack
  git:
    repo: 'https://github.com/secgroundzero/SharpAttack'
    dest: /opt/SharpAttack


- name: Cloning LinkedInt
  git:
    repo: 'https://github.com/vysecurity/LinkedInt'
    dest: /opt/LinkedInt


- name: Cloning ShellcodeConversion
  git:
    repo: 'https://github.com/vysecurity/ShellcodeConversion'
    dest: /opt/ShellcodeConversion


- name: Cloning Dumpert
  git:
    repo: 'https://github.com/outflanknl/Dumpert'
    dest: /opt/Dumpert


- name: Cloning DomLink
  git:
    repo: 'https://github.com/vysecurity/DomLink'
    dest: /opt/DomLink


- name: Cloning RDPassSpray
  git:
    repo: 'https://github.com/xFreed0m/RDPassSpray'
    dest: /opt/RDPassSpray


- name: Installing RDPassSpray requirements
  shell: pip3 install -r /opt/RDPassSpray/requirements.txt



