- name: Installing python-pip
  apt:
    name: 
      - python-pip 
    state: latest

- name: Setting up dotnet sources
  shell: " {{ item }}"
  with_items:
      - sudo apt-get install -y gpg
      - wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
      - mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
      - wget -q https://packages.microsoft.com/config/ubuntu/18.04/prod.list
      - mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
      - chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
      - chown root:root /etc/apt/sources.list.d/microsoft-prod.list

- name: Installing apt-transport-https
  apt:
    name: 
      - apt-transport-https
    state: latest

- name: Updating sources
  shell: apt-get update -y



- name: Installing dotnet2.2
  apt:
    name: 
      - dotnet-runtime-2.2
    state: latest



- name: Downloading Sublime text GPG
  uri:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    follow_redirects: all
    dest: ~/sublimehq-pub.gpg


- name: Installing sublime-text GPG
  command: apt-key add ~/sublimehq-pub.gpg


- name: Updating packages
  shell: apt -qqq install apt-transport-https


- name: Adding sublime-text to sources list
  shell: echo "deb https://download.sublimetext.com/ apt/stable/" > /etc/apt/sources.list.d/sublime-text.list


- name: Updating packages
  shell: apt -qqq update


- name: Installing sublime-text editor
  apt:
    name: 
      - sublime-text
    state: latest


- name: Cloning Tetanus 
  git:
    repo: 'https://github.com/secgroundzero/tetanus'
    dest: /opt/tetanus

- name: Cloning ad-ldap-enum 
  git:
    repo: 'https://github.com/CroweCybersecurity/ad-ldap-enum'
    dest: /opt/ad-ldap-enum

- name: Cloning LinEnum
  git:
    repo: 'https://github.com/rebootuser/LinEnum'
    dest: /opt/LinEnum

- name: Cloning Responder
  git:
    repo: 'https://github.com/lgandx/Responder'
    dest: /opt/Responder

- name: Cloning Unicorn
  git:
    repo: 'https://github.com/trustedsec/unicorn'
    dest: /opt/Unicorn

- name: Cloning ropnop's windapsearch
  git:
    repo: 'https://github.com/ropnop/windapsearch'
    dest: /opt/windapsearch


- name: Installing python-ldap
  apt:
    name: 
      - python-ldap 
    state: latest

- name: Installing pip3
  apt:
    name: 
      - python3-pip 
    state: latest


- name: Cloning ropnop's Kerberos Scripts
  git:
    repo: 'https://github.com/ropnop/kerberos_windows_scripts'
    dest: /opt/kerberos_windows_scripts

- name: Cloning nishang
  git:
    repo: 'https://github.com/samratashok/nishang'
    dest: /opt/nishang

- name: Cloning Sharpshooter
  git:
    repo: 'https://github.com/mdsecactivebreach/SharpShooter'
    dest: /opt/Sharpshooter


- name: Cloning PyKerberoast
  git:
    repo: 'https://github.com/skelsec/PyKerberoast'
    dest: /opt/PyKerberoast


- name: Cloning hidemyps
  git:
    repo: 'https://github.com/cheetz/hidemyps'
    dest: /opt/hidemyps


- name: Cloning PowerShell Empire
  git:
    repo: 'https://github.com/EmpireProject/Empire'
    dest: /opt/Empire

- name: Installing Empire
  command: bash /opt/Empire/setup/install.sh



- name: Cloning bin2c
  git:
    repo: 'https://github.com/gwilymk/bin2c'
    dest: /opt/bin2c


- name: Compiling bin2c
  command: gcc -o /opt/bin2c/bin2c /opt/bin2c/bin2c.c


- name: Installing Libre Office
  apt:
    name: 
      - libreoffice 
    state: latest


- name: Installing PowerShell
  apt:
    name: 
      - powershell
    state: latest


- name: Cloning Invoke-Obfuscation
  git:
    repo: 'https://github.com/danielbohannon/Invoke-Obfuscation'
    dest: /opt/Invoke-Obfuscation


- name: Cloning SprayingToolkit
  git:
    repo: 'https://github.com/byt3bl33d3r/SprayingToolkit'
    dest: /opt/SprayingToolkit


- name: Instaling SprayingToolkit
  command: sudo -H pip3 install -r /opt/SprayingToolkit/requirements.txt


- name: Cloning krbrelayx
  git:
    repo: 'https://github.com/dirkjanm/krbrelayx'
    dest: /opt/krbrelayx

  
- name: Cloning WitnessMe
  git:
    repo: 'https://github.com/byt3bl33d3r/WitnessMe'
    dest: /opt/WitnessMe


- name: Instaling WitnessMe
  command: pip3 install -r /opt/WitnessMe/requirements.txt


- name: Downloading Java Oracle 8
  shell: " {{ item }}"
  with_items: 
      - wget -q -O ~/Desktop/java.tgz $(curl -s https://www.java.com/en/download/linux_manual.jsp | grep -E ".*x64.*javadl" | grep -v "RPM" | sed "s/.*href=\"//g;s/\".*//g" | head -n 1) 
      
- name: Extracting Java to ~/Desktop
  unarchive:
    src: ~/Desktop/java.tgz
    dest: ~/Desktop/

- name: Deleting java archives
  file:
    path: ~/Desktop/java.tgz
    state: absent

- name: Renaming java for ease of transfer
  shell: mv ~/Desktop/jre* ~/Desktop/java_jre


- name: Moving Java to the right location
  shell: " {{ item }}"
  with_items:
      - mkdir /opt/java && mv ~/Desktop/java_jre /opt/java
      - update-alternatives --install "/usr/bin/java" "java" "/opt/java/java_jre/bin/java" 1
      - update-alternatives --set java /opt/java/java_jre/bin/java

- name: Cloning SauronEye
  git:
    repo: 'https://github.com/vivami/SauronEye'
    dest: /opt/SauronEye


- name: Compiling SauronEye
  shell: " {{ item }}"
  with_items: 
      - xbuild /p:Configuration=Release /opt/SauronEye/src/SauronEye/SauronEye.sln
      - mv /opt/SauronEye/src/SauronEye/bin/Release/SauronEye.exe /opt/SauronEye/src/SauronEye/


- name: Cloning Covenant
  git:
    repo: 'git clone --recurse-submodules https://github.com/cobbr/Covenant'
    recursive: yes 
    track_submodules: yes
    dest: /opt/Covenant


- name: Compiling Covenant
  shell: dotnet build /opt/Covenant/Covenant/



#- name: Compiling Rubeus
#  shell: " {{ item }}"
#  with_items: 
#      - xbuild /p:Configuration=Release /opt/Rubeus/Rubeus.sln
#      - mv /opt/Rubeus/Rubeus/bin/Release/Rubeus.exe /opt/csharp_tools/


#- name: Cloning SeatBelt
#  git:
#    repo: 'https://github.com/GhostPack/Seatbelt'
#    dest: /opt/SeatBelt

#- name: Compiling SeatBelt
#  shell: " {{ item }}"
#  with_items: 
#      - xbuild /p:Configuration=Release /opt/SeatBelt/SeatBelt.sln
#      - mv /opt/SeatBelt/Rubeus/bin/Release/SauronEye.exe /opt/csharp_tools/








