- name: Cloning Tetanus 
  git:
    repo: 'https://github.com/secgroundzero/tetanus'
    dest: /opt/tetanus

- name: Cloning ad-ldap-enum 
  git:
    repo: 'https://github.com/CroweCybersecurity/ad-ldap-enum'
    dest: /opt/ad-ldap-enum

- name: Cloning LinEnum
  git:
    repo: 'https://github.com/rebootuser/LinEnum'
    dest: /opt/LinEnum

- name: Cloning Responder
  git:
    repo: 'https://github.com/lgandx/Responder'
    dest: /opt/Responder

- name: Cloning Unicorn
  git:
    repo: 'https://github.com/trustedsec/unicorn'
    dest: /opt/Unicorn

- name: Cloning ropnop's windapsearch
  git:
    repo: 'https://github.com/ropnop/windapsearch'
    dest: /opt/windapsearch

- name: Setting up windapsearch
  command: pip install python-ldap


- name: Cloning ropnop's Kerberos Scripts
  git:
    repo: 'https://github.com/ropnop/kerberos_windows_scripts'
    dest: /opt/kerberos_windows_scripts

- name: Cloning nishang
  git:
    repo: 'https://github.com/samratashok/nishang'
    dest: /opt/nishang

- name: Cloning Sharpshooter
  git:
    repo: 'https://github.com/mdsecactivebreach/SharpShooter'
    dest: /opt/Sharpshooter




